### ISSUE TITLE
ID from Profilespec

### ISSUE THREAD

**Issue by davidrib** [muzzley/yun-muzzley-lock#1]
One thing I can understand, why triggers and actions have a different id?
Were I get that ID? Is from Apps (UUID)?

Thanks
David Ribeiro

**Comment by jorgeclaro** [comment]
Hi,

Those ids should be leaved blank, on our developers website.
They will be all generated by our cloud services, as soon as you save your new profile specification.

Jorge Claro

**Comment by davidrib** [comment]
Wow, thank you for answering a Sunday morning, I'm trying to save the profile but the web-editor not let me,  he does not complain of any error and  not let me save anything,  I press the button "save changes" but it does nothing
I've tried the "FireFox" and "GoogleChrome" and nothing happens

Thanks for the help!
David Ribeiro

**Comment by jorgeclaro** [comment]
Ok. Please, send me an e-mail with your full profilespec JSON configuration. I will try to figure out if there is something wrong with it.
E-mail: jorge.claro@muzzley.com

Cheers

**Comment by davidrib** [comment]
I'm trying use the exemple from https://github.com/muzzley/yun-muzzley-lock
To open the dor, a learn starting point to know more about muzzley api

**Comment by jorgeclaro** [comment]
There is a known issue on our developers website, where the tile info is not shown when those fields are still empty. Sorry for not remembering that right from the beginning. I just updated the profile spec on the repository with a tile sample for the lock. With that JSON you already should be be able to save it without problems.

Just update me, if you were successful.
Cheers

**Comment by davidrib** [comment]
Ok now I have all set, the new profile file "works" (is accepted), but I can't discover the yun in my network, the configuration file example from https://github.com/muzzley/arduino-ciao-muzzley-connector is correct? in the profilespec.json file the ip is localhost an the components I thing they are not compatible,  is not mentioned temp-sensor1 and the component "Lock" does not have the same name?
I have only the ports 22,53,80,443 open on yun, they are the same after I start the ciao.

Thanks for the help
David Ribeiro

**Comment by davidrib** [comment]
I also think him gets stuck in line 107 ("`r = requests.post(register_url, data=json.dumps(register_body), headers=register_headers)`") in muzzleyclient.py
I'm tried debug it, but I could be wrong.

Thanks in advance,
David Ribeiro

**Comment by jorgeclaro** [comment]
Once you have your profile spec saved, you need to add your e-mail address to your Muzzley app access list, and set it to use UPNP discovery. Yes, the configuration file **muzzley.json.conf** present on the https://github.com/muzzley/arduino-ciao-muzzley-connector repository, is correct. It is only related with the internal Ciao server running on the Arduino it self (the localhost address), and the Muzzley public endpoint addresses.

The Muzzley app credentials, should be added to the **muzzley.json.conf** in the **/etc/muzzley/** folder. The same where is located the **device_key.key** file (when present, and not volatile). I know that may be a little confusing, but yes, both of the configuration files have the same name (just following the Ciao naming convention).

You are right, the Arduino .ino script and the Muzzley components array (and properties) should have the same names, as the ones configured on our developers website. The example in the https://github.com/muzzley/arduino-ciao-muzzley-connector repository documentation has a second component just as an example, for a more complex device.

On this Lock example, there isn´t any credential configuration file, but I will probably add one. Even without the tokens, it will probably make the example a bit easier to understand and to run it, without any more hassles.

**Comment by davidrib** [comment]
Thanks for the help, now I have other issue on the ciao side,  the linino don't speak with the Atmega32U4. Firstly they don't have the same baud rate (linino 250000, 32u4 115200 on your example), but even if I change the baud-rate to 250k does not not work. Is not hardware fault because the "Yún Serial Terminal" works with no problems. The only solution to change baud-rate on linux side is to compile the kernel, and I never do it. If you have any advice I appreciate.
The ciao works on the linux side because If I enter a  "run-ciao" command on terminal, I can now configure the muzzley app on smartphone, but it can open the lock and the terminal gets completely locked.
Do you want i close this isue and open other?

Thanks
David Ribeiro

**Comment by jorgeclaro** [comment]
Great to hear that.

For the baud-rate, just change the Ciao.begin(115000) on the Arduino script to Ciao.begin(250000), as you said. If you leave the #define DEBUG, you will need to have the serial terminal open, to start it (Check if there isn´t any Ciao process running in the background and use the 32u4 reset button to start it. The Arduino script will start the Ciao server on the Linino OS by it self). Besides that, if you are still having problems, check if the Linino IO functionality is disabled. The board GPIO pins must be controlled directly by the Atmega 32u4.

I will close this issue since the subject already changed a bit. Please, open another one if you continue to have problems connecting the 32u4 script to the Ciao server.

Thanks

**Comment by davidrib** [comment]
Only for note:
To activate the console again,I need to change the file /etc/inittab

from:

::sysinit:/etc/init.d/rcS S boot
::shutdown:/etc/init.d/rcS K shutdown
ttySPI0::respawn:/bin/ash --login 

To:

::sysinit:/etc/init.d/rcS S boot
::shutdown:/etc/init.d/rcS K shutdown
#ttySPI0::respawn:/bin/ash --login 
ttyATH0::askfirst:/bin/ash --login

**Comment by jorgeclaro** [comment]
Thanks for the tip.

We hope that you enjoyed playing with this lock example.
If you remember any other useful use-case for this Ciao connector or any other suggestion for the Muzzley app it self, please let us know.

Cheers,
Jorge Claro
